#!/usr/bin/env python3
# В начале файла generator.py добавьте импорт
import os
import sys
import shutil
import json
import argparse
from datetime import datetime  # Добавьте эту строку

# Остальной код остается без изменений
class SiteGenerator:
    def __init__(self, project_name='my-booking-site', template_dir=None):
        """
        Инициализация генератора сайта
        
        :param project_name: Название проекта
        :param template_dir: Директория с шаблонами (если не указана, используется встроенный)
        """
        self.project_name = project_name
        self.base_dir = os.path.abspath(os.path.dirname(__file__))
        
        # Определяем директорию шаблонов
        if template_dir:
            self.template_dir = os.path.abspath(template_dir)
        else:
            self.template_dir = os.path.join(self.base_dir, 'site_templates', 'booking')

    def create_project_structure(self, output_path=None):
        """
        Создание структуры проекта
        
        :param output_path: Путь для создания проекта (по умолчанию - текущая директория)
        """
        if not output_path:
            output_path = os.path.join(os.getcwd(), self.project_name)
        
        # Создаем основные директории
        dirs = [
            output_path,
            os.path.join(output_path, 'js'),
            os.path.join(output_path, 'css')
        ]
        
        for dir_path in dirs:
            os.makedirs(dir_path, exist_ok=True)
        
        # Копируем файлы из шаблона
        template_files = [
            ('index.html', 'index.html'),
            ('login.html', 'login.html'),
            ('registration.html', 'registration.html'),
            ('new-request.html', 'new-request.html'),
            ('requests.html', 'requests.html'),
            ('profile.html', 'profile.html'),
            ('admin.html', 'admin.html'),
            
            ('index.js', os.path.join('js', 'index.js')),
            ('login.js', os.path.join('js', 'login.js')),
            ('registration.js', os.path.join('js', 'registration.js')),
            ('new-request.js', os.path.join('js', 'new-request.js')),
            ('requests.js', os.path.join('js', 'requests.js')),
            ('profile.js', os.path.join('js', 'profile.js')),
            ('admin.js', os.path.join('js', 'admin.js')),
            ('auth.js', os.path.join('js', 'auth.js')),
            
            ('styles.css', os.path.join('css', 'styles.css')),
            ('index.css', os.path.join('css', 'index.css')),
            ('admin.css', os.path.join('css', 'admin.css'))
        ]
        
        for source_file, dest_file in template_files:
            source_path = os.path.join(self.template_dir, source_file)
            dest_path = os.path.join(output_path, dest_file)
            
            if os.path.exists(source_path):
                shutil.copy2(source_path, dest_path)
            else:
                print(f"Внимание: файл {source_file} не найден в шаблоне")
        
        # Создаем файл конфигурации проекта
        config = {
            "name": self.project_name,
            "version": "1.0.0",
            "description": "Booking site generated by site generator",
            "created_at": str(datetime.now())
        }
        
        with open(os.path.join(output_path, 'site_config.json'), 'w', encoding='utf-8') as f:
            json.dump(config, f, ensure_ascii=False, indent=4)
        
        print(f"Проект '{self.project_name}' успешно создан в {output_path}")

    def customize_project(self, config_file=None):
        """
        Кастомизация проекта на основе конфигурационного файла
        
        :param config_file: Путь к файлу конфигурации
        """
        if not config_file or not os.path.exists(config_file):
            print("Файл конфигурации не указан или не существует")
            return
        
        try:
            with open(config_file, 'r', encoding='utf-8') as f:
                custom_config = json.load(f)
            
            # Здесь можно добавить логику кастомизации сайта
            # Например, замена логотипа, цветовой схемы, контактных данных и т.д.
            print("Проект успешно кастомизирован")
        except json.JSONDecodeError:
            print("Ошибка парсинга JSON-файла конфигурации")
        except Exception as e:
            print(f"Ошибка кастомизации: {e}")

def main():
    parser = argparse.ArgumentParser(description='Генератор сайта для системы бронирования')
    parser.add_argument('action', choices=['create', 'customize'], 
                        help='Действие: создание или кастомизация проекта')
    parser.add_argument('--name', default='my-booking-site', 
                        help='Название проекта (по умолчанию: my-booking-site)')
    parser.add_argument('--output', 
                        help='Путь для создания проекта')
    parser.add_argument('--config', 
                        help='Путь к файлу конфигурации для кастомизации')
    
    args = parser.parse_args()
    
    generator = SiteGenerator(project_name=args.name)
    
    if args.action == 'create':
        generator.create_project_structure(args.output)
    elif args.action == 'customize':
        if not args.config:
            print("Для кастомизации требуется файл конфигурации (--config)")
            sys.exit(1)
        generator.customize_project(args.config)

if __name__ == '__main__':
    main()